  - type: cron
    name: outbound-caller
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python outbound.py"
    instanceType: free
    schedule: "*/5 * * * *" # Runs every 5 minutes
    envVars:
      - fromGroup: safemama-secrets
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: ai-voice-agent
          property: url
    # ADDED: secretFiles section for consistency and future use
    secretFiles:
      - key: GOOGLE_APPLICATION_CREDENTIALS_FILE
        fromGroup: safemama-secrets
        name: google-creds.json

