services:
  # Web Service for the main Flask App (app.py)
  - type: web
    name: ai-voice-agent
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app"
    instanceType: free
    envVars:
      - fromGroup: safemama-secrets
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: ai-voice-agent
          property: url
    secretFiles:
      - key: GOOGLE_APPLICATION_CREDENTIALS_FILE
        fromGroup: safemama-secrets
        name: google-creds.json
